# Generated by Django 2.1 on 2020-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=5)),
                ('quantity', models.IntegerField(default=1)),
                ('img_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
