# Generated by Django 2.1 on 2020-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=5)),
                ('stock', models.IntegerField(max_length=3)),
                ('img_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
