# Generated by Django 3.2.2 on 2021-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200911_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.AddField(
            model_name='product',
            name='img_upload',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
